-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2019.2 Schlumberger
-- User name   : JLiu38
-- Date        : Saturday, August 17 2019 00:15:23
-- Project     : ECLIPSE_CONVERT.pet
-- Generated ]

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 1
  TRANY 0 6 6 16 16 1 1 /
  TRANY 0 6 6 16 16 2 2 /
  TRANY 0 6 6 16 16 3 3 /
  TRANY 0 6 6 16 16 9 9 /
  TRANY 0 6 6 16 16 10 10 /
  TRANY 0 6 6 16 16 11 11 /
  TRANY 0 6 6 16 16 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 2
  TRANX 0 6 6 16 16 1 1 /
  TRANX 0 6 6 16 16 2 2 /
  TRANX 0 6 6 16 16 3 3 /
  TRANX 0 6 6 16 16 9 9 /
  TRANX 0 6 6 16 16 10 10 /
  TRANX 0 6 6 16 16 11 11 /
  TRANX 0 6 6 16 16 12 12 /
  TRANX 0 6 6 15 15 1 1 /
  TRANX 0 6 6 15 15 2 2 /
  TRANX 0 6 6 15 15 3 3 /
  TRANX 0 6 6 15 15 9 9 /
  TRANX 0 6 6 15 15 10 10 /
  TRANX 0 6 6 15 15 11 11 /
  TRANX 0 6 6 15 15 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 3
  TRANY 0 7 7 14 14 1 1 /
  TRANY 0 7 7 14 14 2 2 /
  TRANY 0 7 7 14 14 3 3 /
  TRANY 0 7 7 14 14 9 9 /
  TRANY 0 7 7 14 14 10 10 /
  TRANY 0 7 7 14 14 11 11 /
  TRANY 0 7 7 14 14 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 4
  TRANX 0 7 7 14 14 1 1 /
  TRANX 0 7 7 14 14 2 2 /
  TRANX 0 7 7 14 14 3 3 /
  TRANX 0 7 7 14 14 9 9 /
  TRANX 0 7 7 14 14 10 10 /
  TRANX 0 7 7 14 14 11 11 /
  TRANX 0 7 7 14 14 12 12 /
  TRANX 0 7 7 13 13 1 1 /
  TRANX 0 7 7 13 13 2 2 /
  TRANX 0 7 7 13 13 3 3 /
  TRANX 0 7 7 13 13 9 9 /
  TRANX 0 7 7 13 13 10 10 /
  TRANX 0 7 7 13 13 11 11 /
  TRANX 0 7 7 13 13 12 12 /
  TRANX 0 7 7 12 12 1 1 /
  TRANX 0 7 7 12 12 2 2 /
  TRANX 0 7 7 12 12 3 3 /
  TRANX 0 7 7 12 12 9 9 /
  TRANX 0 7 7 12 12 10 10 /
  TRANX 0 7 7 12 12 11 11 /
  TRANX 0 7 7 12 12 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 5
  TRANY 0 8 8 11 11 1 1 /
  TRANY 0 8 8 11 11 2 2 /
  TRANY 0 8 8 11 11 3 3 /
  TRANY 0 8 8 11 11 9 9 /
  TRANY 0 8 8 11 11 10 10 /
  TRANY 0 8 8 11 11 11 11 /
  TRANY 0 8 8 11 11 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 6
  TRANX 0 8 8 11 11 1 1 /
  TRANX 0 8 8 11 11 2 2 /
  TRANX 0 8 8 11 11 3 3 /
  TRANX 0 8 8 11 11 9 9 /
  TRANX 0 8 8 11 11 10 10 /
  TRANX 0 8 8 11 11 11 11 /
  TRANX 0 8 8 11 11 12 12 /
  TRANX 0 8 8 10 10 1 1 /
  TRANX 0 8 8 10 10 2 2 /
  TRANX 0 8 8 10 10 3 3 /
  TRANX 0 8 8 10 10 9 9 /
  TRANX 0 8 8 10 10 10 10 /
  TRANX 0 8 8 10 10 11 11 /
  TRANX 0 8 8 10 10 12 12 /
  TRANX 0 8 8 9 9 1 1 /
  TRANX 0 8 8 9 9 2 2 /
  TRANX 0 8 8 9 9 3 3 /
  TRANX 0 8 8 9 9 9 9 /
  TRANX 0 8 8 9 9 10 10 /
  TRANX 0 8 8 9 9 11 11 /
  TRANX 0 8 8 9 9 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 7
  TRANY 0 9 9 8 8 1 1 /
  TRANY 0 9 9 8 8 2 2 /
  TRANY 0 9 9 8 8 3 3 /
  TRANY 0 9 9 8 8 9 9 /
  TRANY 0 9 9 8 8 10 10 /
  TRANY 0 9 9 8 8 11 11 /
  TRANY 0 9 9 8 8 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 8
  TRANX 0 9 9 8 8 1 1 /
  TRANX 0 9 9 8 8 2 2 /
  TRANX 0 9 9 8 8 3 3 /
  TRANX 0 9 9 8 8 9 9 /
  TRANX 0 9 9 8 8 10 10 /
  TRANX 0 9 9 8 8 11 11 /
  TRANX 0 9 9 8 8 12 12 /
  TRANX 0 9 9 7 7 1 1 /
  TRANX 0 9 9 7 7 2 2 /
  TRANX 0 9 9 7 7 3 3 /
  TRANX 0 9 9 7 7 9 9 /
  TRANX 0 9 9 7 7 10 10 /
  TRANX 0 9 9 7 7 11 11 /
  TRANX 0 9 9 7 7 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 9
  TRANY 0 10 10 6 6 1 1 /
  TRANY 0 10 10 6 6 2 2 /
  TRANY 0 10 10 6 6 9 9 /
  TRANY 0 10 10 6 6 10 10 /
  TRANY 0 10 10 6 6 11 11 /
  TRANY 0 10 10 6 6 12 12 /
  /

EQUALS                                 -- Generated : Petrel
-- Modifier set 'SNARK_CONVERTED', modifier 10
  TRANX 0 10 10 6 6 1 1 /
  TRANX 0 10 10 6 6 2 2 /
  TRANX 0 10 10 6 6 9 9 /
  TRANX 0 10 10 6 6 10 10 /
  TRANX 0 10 10 6 6 11 11 /
  TRANX 0 10 10 6 6 12 12 /
  TRANX 0 10 10 5 5 1 1 /
  TRANX 0 10 10 5 5 2 2 /
  TRANX 0 10 10 5 5 11 11 /
  TRANX 0 10 10 5 5 12 12 /
  /

